#!/bin/bash
if [ "$1" == 'help' ]; then
	echo "$0 CERTFR-2019-AVI-208 : créé une nouvelle page vulnérabilité CERTFR"
else
	if [ ! -n "$1" ]; then
		echo "usage: $0 CERTFR-2019-AVI-208"
	else
		id=$1

		cd ~/Sync/infra-doctech.wiki
		git pull 
		if [ -f "$id.md" ]; then 
			echo "le fichier $id.md existe déjà"
			exit 1
		else
			cp CERTFR-template.md $id.md
			sed -e 's/#ID#/'$id'/' -i $id.md
			git add $id.md
			git commit -m "creation $id"
			git push
		fi
		xdg-open "https://github.com/Epiconcept-Paris/infra-doctech/wiki/$id/_edit"
	fi
fi
