#!/bin/bash
if [ "$1" == 'help' ]; then
	echo "$0 CVE-2019-7308 : créé une nouvelle page CVE"
else
	if [ ! -n "$1" ]; then
		echo "usage: $0 CVE-2019-7308"
	else
		cve=$1

		cd ~/Sync/infra-doctech.wiki
		git pull 
		cp CVE-template.md $cve.md
		sed -e 's/#CVE#/'$cve'/' -i $cve.md
		git add $cve.md
		git commit -m "creation $cve"
		git push
		xdg-open "https://github.com/Epiconcept-Paris/infra-doctech/wiki/$cve"
	fi
fi
