#!/bin/bash
if [ "$1" == 'help' ]; then
	echo "$0 cheminscript [frontaux|bdd|...] : renseigne sur la présence d'un paquet"
else
	if [ ! -n "$1" ]; then
		echo "usage: $0 cheminscript [frontaux|bdd|...]"
	else
		src=$1
		population=$2
		if [ -z "$population" ]; then population='all'; fi
		if [ ! -f "$src" ]; then echo "fichier $src inexistant"; exit 1; fi
		dest=/usr/local/bin/$(basename $src)

		ansible $population -i ~/bin/list_new_servers.txt --one-line --become -m copy -a "src=$src dest=$dest mode=0755 owner=root group=root" -D
	fi
fi
