#!/bin/bash
docbase="$0 chemin_nommé"

if [ "$1" == 'help' || ! -d "$1" ]; then
	echo "$docbase : gère les fichiers rippé pour un cd J'aime Lire"
else
	pathdest=~/Sync/CNotes/Podcasts/JAimeLire
	path=$1
	name=$(basename $path)
	rm $path/01* $path/*.m3u
	detox $path/*
	dest=$pathdest/$name.mp3
	echo "création $dest"
	ffmpeg -loglevel warning -i "concat:$(ls $path/0[234]*.mp3|sort|xargs|sed 's/ /|/g')" -acodec copy $dest
	dest=$pathdest/$name_blagues.mp3
	echo "création $dest"
	cp $path/05*.mp3 $dest
	
fi